version: "3.9"
   
services:

  db:
    image: postgres:16.3

    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=tay_deploy
      - POSTGRES_DB=postgres
      - POSTGRES_USER=dbmasteruser

      
  web:
    build: .
    #command: gunicorn aInc.wsgi -b 0.0.0.0:8000
    command: python3 /tayber/tay_deploy/manage.py runserver 0.0.0.0:8000

    environment:
      - ENVIRONMENT=production
      #- DEBUG=1
      
      

    volumes:
      - .:/tayber/tay_deploy

    ports:

      - "8000:8000"
    depends_on:
      - db
      #- redis
      

    restart: always

  nginx:
    build: ./nginx
    volumes:
      - ./static:/static
      - ./staticfiles:/staticfiles

      - ./media:/mediafiles
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf


    ports:
      - "80:80"
    depends_on:
      - web

    restart: always


  
  #frontend:
    #build:
     # context: ./frontend

      #dockerfile: Dockerfile
    #command: npm start
    #ports:
      #- "3000:3000"

   # depends_on:

     # - web

    #volumes:
     # - ./frontend:/frontend

volumes:
  db:
  static:
  #media:
