# Generated by Django 5.1.2 on 2024-11-04 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_prompttemplate_queryhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('template_type', models.CharField(choices=[('financial', 'Financial Analysis'), ('risk', 'Risk Analysis'), ('md_and_a', 'MD&A Analysis'), ('business', 'Business Overview'), ('legal', 'Legal Proceedings'), ('market', 'Market Analysis'), ('custom', 'Custom Analysis')], max_length=20)),
                ('prompt_template', models.TextField()),
                ('default_parameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('cik', models.CharField(max_length=10, unique=True)),
                ('industry', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Document10K',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_date', models.DateField()),
                ('fiscal_year', models.IntegerField()),
                ('document_url', models.URLField()),
                ('raw_content', models.TextField()),
                ('parsed_content', models.JSONField(default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'ordering': ['-filing_date'],
                'unique_together': {('company', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField()),
                ('parameters', models.JSONField()),
                ('analysis_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.analysistemplate')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.document10k')),
            ],
            options={
                'verbose_name_plural': 'Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=20)),
                ('operating_income', models.DecimalField(decimal_places=2, max_digits=20)),
                ('gross_margin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('operating_margin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('net_margin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_liabilities', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_equity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_assets', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_liabilities', models.DecimalField(decimal_places=2, max_digits=20)),
                ('operating_cash_flow', models.DecimalField(decimal_places=2, max_digits=20)),
                ('investing_cash_flow', models.DecimalField(decimal_places=2, max_digits=20)),
                ('financing_cash_flow', models.DecimalField(decimal_places=2, max_digits=20)),
                ('free_cash_flow', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quick_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('debt_to_equity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('return_on_equity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('return_on_assets', models.DecimalField(decimal_places=2, max_digits=5)),
                ('asset_turnover', models.DecimalField(decimal_places=2, max_digits=5)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.document10k')),
            ],
        ),
        migrations.CreateModel(
            name='RiskMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_categories', models.JSONField()),
                ('risk_scores', models.JSONField()),
                ('year_over_year_changes', models.JSONField()),
                ('key_risk_indicators', models.JSONField()),
                ('mitigation_strategies', models.JSONField()),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.document10k')),
            ],
        ),
    ]
