# Generated by Django 5.1.2 on 2024-11-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_analysistemplate_company_document10k_analysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('bot_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextGenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.TextField()),
                ('max_tokens', models.PositiveIntegerField()),
                ('bad_words', models.TextField(blank=True, null=True)),
                ('stop_words', models.TextField(blank=True, null=True)),
                ('pad_id', models.IntegerField(default=2)),
                ('end_id', models.IntegerField(default=2)),
            ],
        ),
    ]
